### ISSUE TITLE
How does PySyft know the IP address of the worker?

### ISSUE THREAD

**Issue by tonyreina** [OpenMined/sgx-experiments#1]
## Question
**Describe your question in ONE SENTENCE.**
How does PySyft know the IP address of the worker in the federation?

## Further Information
Describe your question in greater length here.
worker1 = sy.VirtualWorker(hook, id="worker1")

I think the experiments here are just a virtual federation where everything exists on a single machine. Is there any method for a real worker that is on another machine? If so, how do we specify the IP address, port, and TLS certificates?

## Screenshots
If applicable, add screenshots to help explain your question.

## System Information
 - OS Version: [e.g. 22]
 - Language Version: [e.g. Python 3.7, Node 10.18.1]
 - Package Manager Version: [e.g. Conda 4.6.1, NPM 6.14.1]

**Comment by 0xHericles** [comment]
Hello, @tonyreina. Yes, as you said, the experiments here are just a virtual federation where everything exists on a single machine. We'll be working on more experiments to add support for real workers in different machines.

**Comment by tonyreina** [comment]
Got it. Thanks. Would something like PyGrid be the eventual evolution for the true multinode?

**Comment by 0xHericles** [comment]
> Got it. Thanks. Would something like PyGrid be the eventual evolution for the true multinode?

Yes
